export async function POST(request) {
    try {
        const body = await request.json();

        // This URL should be the Web App URL generated by Google Apps Script
        const googleScriptUrl = process.env.GOOGLE_SCRIPT_URL;

        if (!googleScriptUrl) {
            console.error("GOOGLE_SCRIPT_URL is not defined in environment variables.")
            return Response.json({ message: "Server configuration error" }, { status: 500 });
        }

        const res = await fetch(googleScriptUrl, {
            method: "POST",
            // Depending on the Google App Script, sometimes it expects form-url-encoded or JSON. 
            // We'll send JSON for now. The script must be configured to read JSON from postData.
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify(body),
        });

        // Some Google Apps Script responses might not be standard JSON if configured improperly
        const result = await res.text();

        if (res.ok) {
            return Response.json({ success: true, message: "Interest registered successfully", data: result }, { status: 200 });
        } else {
            return Response.json({ success: false, message: "Failed to register interest to Google Sheet", error: result }, { status: res.status });
        }

    } catch (error) {
        console.error("Error submitting interest:", error);
        return Response.json({ success: false, message: "An error occurred", error: error.message }, { status: 500 });
    }
}
